export const genre=[
      "All Genre",
      "Fantasy",
      "Thriller",
      "SciFi",
      "Action",
      "Periodic",
      "Comedy",
      "Drama",
      "Crime",
      "Animation",
      "Fiction",
      "Horror",
      "Adventure",
      "Romantic",
    ];